# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fee',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_in_shop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='coupon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
