# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0006_auto_20160402_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_tracker.PurchaseOrder')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_tracker.PurchaseOrderStatus')),
            ],
        ),
    ]
