# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0007_statuslog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statuslog',
            table='status_log',
        ),
    ]
