# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0008_auto_20160416_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='admin_comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user_comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
